const producpollos =[
{id:1, nombre: "", Precio:0, categoria: "", imagen:"/img/1.png" },
{id:2, nombre: "", Precio:0, categoria: "" , imagen:"/img/2.png" },
{id:3, nombre: "", Precio:0, categoria: "" , imagen:"/img/3.png" },
{id:4, nombre: "", Precio:0, categoria: "" , imagen:"/img/4.png" },
{id:5, nombre: "", Precio:0, categoria: "" , imagen:"/img/5.png" },
{id:6, nombre: "", Precio:0, categoria: "" , imagen:"/img/6.png" },
{id:7, nombre: "", Precio:0, categoria: "" , imagen:"/img/7.png" },
{id:8, nombre: "", Precio:0, categoria: "" , imagen:"/img/8.png" },
{id:9, nombre: "", Precio:0, categoria: "" , imagen:"/img/9.png" },
{id:10, nombre: "", Precio:0, categoria: "" , imagen:"/img/10.png" },
{id:11, nombre: "", Precio:0, categoria: "" , imagen:"/img/11.png" },
{id:12, nombre: "", Precio:0, categoria: "" , imagen:"/img/12.png" },
{id:13, nombre: "", Precio:0, categoria: "" , imagen:"/img/13.png" },
{id:14, nombre: "", Precio:0, categoria: "" , imagen:"/img/14.png" },
{id:15, nombre: "", Precio:0, categoria: "" , imagen:"/img/15.png" },
{id:16, nombre: "", Precio:0, categoria: "" , imagen:"/img/16.png" },
{id:17, nombre: "", Precio:0, categoria: "" , imagen:"/img/17.png" },
{id:18, nombre: "", Precio:0, categoria: "" , imagen:"/img/18.png" },
{id:19, nombre: "", Precio:0, categoria: "" , imagen:"/img/19.png" },
{id:20, nombre: "", Precio:0, categoria: "" , imagen:"/img/20.png" },
{id:21, nombre: "", Precio:0, categoria: "" , imagen:"/img/21.png" },
{id:22, nombre: "", Precio:0, categoria: "" , imagen:"/img/22.png" },
{id:23, nombre: "", Precio:0, categoria: "" , imagen:"/img/23.png" },
{id:24, nombre: "", Precio:0, categoria: "" , imagen:"/img/24.png" },
{id:25, nombre: "", Precio:0, categoria: "" , imagen:"/img/25.png" },
{id:26, nombre: "", Precio:0, categoria: "" , imagen:"/img/26.png" },
{id:27, nombre: "", Precio:0, categoria: "" , imagen:"/img/27.png" },
{id:28, nombre: "", Precio:0, categoria: "" , imagen:"/img/27.png" },
{id:29, nombre: "", Precio:0, categoria: "" , imagen:"/img/28.png" },
{id:30, nombre: "", Precio:0, categoria: "" , imagen:"/img/29.png" },
{id:31, nombre: "", Precio:0, categoria: "" , imagen:"/img/30.png" },
{id:32, nombre: "", Precio:0, categoria: "" , imagen:"/img/31.png" },
{id:33, nombre: "", Precio:0, categoria: "" , imagen:"/img/32.png" },
{id:34, nombre: "", Precio:0, categoria: "" , imagen:"/img/33.png" },
{id:35, nombre: "", Precio:0, categoria: "" , imagen:"/img/34.png" },
{id:36, nombre: "", Precio:0, categoria: "" , imagen:"/img/35.png" },
{id:37, nombre: "", Precio:0, categoria: "" , imagen:"/img/36.png" },
{id:38, nombre: "", Precio:0, categoria: "" , imagen:"/img/37.png" },
{id:39, nombre: "", Precio:0, categoria: "" , imagen:"/img/38.png" },
{id:40, nombre: "", Precio:0, categoria: "" , imagen:"/img/39.png" },

]

console.log(producpollos[1]);