const producpollos =[
{id:1, nombre: "Pernil mixto Refrigerado", Precio:5300 , categoria: "Pollo Fresco", imagen:"/img/1.png" },
{id:2, nombre: "Pollo Refrigerado", Precio:7000, categoria: "Pollo Fresco" , imagen:"/img/2.png" },
{id:3, nombre: "Pernil Blanco", Precio:6000, categoria: "Pollo Fresco" , imagen:"/img/3.png" },
{id:4, nombre: "Ala Refrigerada", Precio:7350, categoria: "Pollo Fresco" , imagen:"/img/4.png" },
{id:5, nombre: "Ala Campesina", Precio:7900, categoria: "Pollo Campesino" , imagen:"/img/5.png" },
{id:6, nombre: "Ala Mixta Campesina", Precio:8900, categoria: "Pollo Campesino" , imagen:"/img/6.png" },
{id:7, nombre: "Ala Mixta Blanca", Precio:8200, categoria: "Pollo Fresco" , imagen:"/img/7.png" },
{id:8, nombre: "Colombina de Ala", Precio:9900, categoria: "Pollo Fresco" , imagen:"/img/8.png" },
{id:9, nombre: "Churrasco sin Piel", Precio:11200, categoria: "Pollo Fresco" , imagen:"/img/9.png" },
{id:10, nombre: "Lomitos de Pechuga", Precio:10500, categoria: "Pollo Fresco" , imagen:"/img/10.png" },
{id:11, nombre: "Alas", Precio:7500, categoria: "Pollo Fresco" , imagen:"/img/11.png" },
{id:12, nombre: "Filete de Pollo Marinado", Precio:15000, categoria: "Bandejas" , imagen:"/img/12.png" },
{id:13, nombre: "Pechuga Campesina", Precio:10000, categoria: "Pollo Campesino" , imagen:"/img/13.png" },
{id:14, nombre: "Pernil Campesino", Precio:6800, categoria: "Pollo Campesino" , imagen:"/img/14.png" },
{id:15, nombre: "Pierna Pernil", Precio:6750, categoria: "Pollo Fresco" , imagen:"/img/15.png" },
{id:16, nombre: "Cuadritos de Pechuga", Precio:9700, categoria: "Pollo Fresco" , imagen:"/img/16.png" },
{id:17, nombre: "Cuartos de Piernas Adobadas", Precio: 14000, categoria: "Bandejas" , imagen:"/img/17.png" },
{id:18, nombre: "Filete de Pechuga sin Hueso", Precio:10500, categoria: "Pollo Campesino" , imagen:"/img/18.png" },
{id:19, nombre: "Filete de Pechuga Porcionada", Precio:11000, categoria: "Pollo Fresco" , imagen:"/img/19.png" },
{id:20, nombre: "Pernil Con Rabadilla sin Piel", Precio:8200, categoria: "Pollo Fresco" , imagen:"/img/20.png" },
{id:21, nombre: "Piernas sin Piel", Precio:6500, categoria: "Pollo Fresco" , imagen:"/img/21.png" },
{id:22, nombre: "Varitas de Pollo de Pechuga", Precio:30000, categoria: "Pollo Fresco" , imagen:"/img/22.png" },
{id:23, nombre: "Pernil sin Rabadilla Campesino", Precio:8150, categoria: "Pollo Campesino" , imagen:"/img/23.png" },
{id:24, nombre: "Pierna Campesina", Precio:8500, categoria: "Pollo Campesino" , imagen:"/img/24.png" },
{id:25, nombre: "Pernil Mixto sin Piel", Precio:6900, categoria: "Pollo Fresco" , imagen:"/img/25.png" },
{id:26, nombre: "Pechuga sin Piel", Precio:10400, categoria: "Pollo Fresco" , imagen:"/img/26.png" },
{id:27, nombre: "Menudencia", Precio:4500, categoria: "Pollo Fresco" , imagen:"/img/27.png" },
{id:28, nombre: "Medio pollo Relleno Tajado", Precio:37500, categoria: "Especialidades de Pollo" , imagen:"/img/28.png" },
{id:29, nombre: "Pastel de Pollo Hawaiano", Precio:35000, categoria: "Especialidades de Pollo" , imagen:"/img/29.png" },
{id:30, nombre: "Jamon de Pollo", Precio:24500, categoria: "Especialidades de Pollo" , imagen:"/img/31.png" },
{id:31, nombre: "Pechuga Rellena de Ciruelas", Precio:29000, categoria: "Especialidades de Pollo" , imagen:"/img/30.png" },
{id:32, nombre: "Molipollo", Precio:7000, categoria: "Salsamentaria" , imagen:"/img/32.png" },
{id:33, nombre: "Salchicha Ahumada", Precio:19400, categoria: "Salsamentaria" , imagen:"/img/33.png" },
{id:34, nombre: "Higados de Pollo", Precio:4800, categoria: "Bandejas" , imagen:"/img/34.png" },
{id:35, nombre: "Molejas de Pollo", Precio:4500, categoria: "Bandejas" , imagen:"/img/35.png" },
{id:36, nombre: "Pollo en Rodajas", Precio:7500, categoria: "Bandejas" , imagen:"/img/36.png" },
{id:37, nombre: "Pollo en Bandeja", Precio:9000, categoria: "Bandejas" , imagen:"/img/37.png" },
{id:38, nombre: "Bandeja de Muslos sin Piel y Deshuesados", Precio:10000, categoria: "Bandejas" , imagen:"/img/38.png" },
{id:39, nombre: "Alitas de Pollo Adobadas", Precio:14000, categoria: "Bandejas" , imagen:"/img/39.png" },
{id:40, nombre: "Alitas a la BBQ", Precio:16000, categoria: "Bandejas" , imagen:"/img/40.png" },

]

console.log(producpollos);

